name: Update IP list

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Update
      env:
        SCANNER_TOKEN: ${{ secrets.SCANNER_TOKEN }}
      run: |-
        curl http://scanner.matdoes.dev/ips?t=${{ secrets.SCANNER_TOKEN }} > ips
    - name: Commit and push if it changed
      run: |-
        git config user.name "bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update active IPs for ${timestamp}" || exit 0
        git push
